export { default as Category } from './Category'
export { default as Checkout } from './Checkout'
export { default as Home } from './Home'
export { default as NotFound } from './NotFound'
export { default as Product } from './Product'
